using Xunit;

namespace CellSharp.Tests;

/// <summary>Compiles and exercises the canonical snippets mirrored by README, getting-started material, and the AI agent guide.</summary>
public sealed class ExcelDocumentationExamplesTests
{
    [Fact]
    public void ConventionBasedWriteAndReadExampleWorks()
    {
        var path = TemporaryPath();
        try
        {
            Excel.Write(path, [new Customer { Id = 1, Name = "Acme" }]);
            var result = Excel.Read<Customer>(path);

            Assert.True(result.IsValid);
            Assert.Equal("Acme", Assert.Single(result.Rows).Name);
        }
        finally { Delete(path); }
    }

    [Fact]
    public void SchemaTemplateAndMultiSheetExamplesWork()
    {
        var path = TemporaryPath();
        var template = TemporaryPath();
        var schema = Excel.Schema<Customer>()
            .SheetName("Customers")
            .AsTable("CustomersTable")
            .Column(customer => customer.Id)
            .Column(customer => customer.Name, column => column.Header("Customer name"))
            .Build();
        try
        {
            Excel.CreateTemplate(template, schema);
            Excel.Workbook()
                .AddSheet([new Customer { Id = 1, Name = "Acme" }], schema, sheet =>
                {
                    sheet.Title("Customers", "A1:D2");
                    sheet.DataStartAt("A4");
                })
                .AddSheet("Notes", sheet => sheet.Note("Generated by CellSharp.", "A1:D2"))
                .Write(path);

            var result = Excel.Read<Customer>(path, schema);
            Assert.True(result.IsValid);
            Assert.Equal("Acme", Assert.Single(result.Rows).Name);
        }
        finally { Delete(path); Delete(template); }
    }

    [Fact]
    public void ValidationFormulaAndDiagnosticsExampleWorks()
    {
        var path = TemporaryPath();
        var schema = Excel.Schema<Order>()
            .Column(order => order.Quantity, column => column.Range(1, 1000))
            .Column(order => order.Price)
            .Column(order => order.Total, column => column.Formula(context => $"=A{context.Row}*B{context.Row}").Format("#,##0.00"))
            .Build();
        try
        {
            Excel.Write(path, [new Order { Quantity = 2, Price = 12.5m }], schema);
            var result = Excel.Read<Order>(path, schema);

            Assert.True(result.IsValid);
            Assert.Equal(2, Assert.Single(result.Rows).Quantity);
        }
        finally { Delete(path); }
    }

    private static string TemporaryPath() => Path.Combine(Path.GetTempPath(), $"cellsharp-docs-{Guid.NewGuid():N}.xlsx");
    private static void Delete(string path) { if (File.Exists(path)) File.Delete(path); }

    private sealed class Customer
    {
        public int Id { get; set; }

        public string Name { get; set; } = "";
    }

    private sealed class Order
    {
        public int Quantity { get; set; }

        public decimal Price { get; set; }

        public decimal Total { get; set; }
    }
}
